---
# Environment specific values, override helm_deploy/hmpps-registers-to-delius-update/values.yaml

generic-service:
  ingress:
    host: registers-to-delius-update-preprod.hmpps.service.justice.gov.uk
  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    PROBATION_ENDPOINT_URL: "https://community-api.pre-prod.delius.probation.hmpps.dsd.io"
    COURT_REGISTER_ENDPOINT_URL: "https://court-register-preprod.hmpps.service.justice.gov.uk"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
