---
# Environment specific values, override helm_deploy/hmpps-registers-to-delius-update/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: registers-to-delius-update-dev.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    PROBATION_ENDPOINT_URL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
    COURT_REGISTER_ENDPOINT_URL: "https://court-register-dev.hmpps.service.justice.gov.uk"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
