---
# Environment specific values, override helm_deploy/court-register/values.yaml

generic-service:
  replicaCount: 4
  ingress:
    host: registers-to-delius-update.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PROBATION_ENDPOINT_URL: "https://community-api.probation.service.justice.gov.uk"
    COURT_REGISTER_ENDPOINT_URL: "https://court-register.hmpps.service.justice.gov.uk"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: digital-prison-service

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
